<<<<<<< HEAD
# Generated by Django 4.1 on 2023-03-28 18:19
=======
# Generated by Django 4.1 on 2023-03-27 17:35
>>>>>>> e4ace045a9e92a17a3df19c44d40a2d024b5a711

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('box_number', models.IntegerField(default=1)),
=======
>>>>>>> e4ace045a9e92a17a3df19c44d40a2d024b5a711
            ],
        ),
    ]
