# Generated by Django 4.1 on 2023-03-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='box_number',
            field=models.IntegerField(default=1),
        ),
    ]
