# Generated by Django 4.1 on 2023-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcards_box_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('box_ID', models.IntegerField()),
                ('question', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Flashcards',
        ),
    ]
