# Generated by Django 4.1 on 2023-03-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_cards_box_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='answer',
            new_name='answers',
        ),
    ]
