# Generated by Django 4.1 on 2023-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_flashcards_delete_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcards',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='flashcards',
            old_name='box_number',
            new_name='box_ID',
        ),
        migrations.RemoveField(
            model_name='flashcards',
            name='answer',
        ),
        migrations.AddField(
            model_name='flashcards',
            name='answers',
            field=models.CharField(default='Brak odpowiedzi', max_length=256),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='question',
            field=models.CharField(max_length=256),
        ),
    ]
